### ISSUE TITLE
无法正常释放config文件

### ISSUE THREAD

**Issue by Wikeolf** [eagle3236/daycount-NBT#2]
报错如下

```
[MCDR] [2021-09-03 11:35:43] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=daycount_nbt@2.0.1,priority=1000,callback=<function on_load at 0x000001D4808B0940>]
Traceback (most recent call last):
  File "D:\Minecraft\生电服\1.16.5\mcdreforged\plugin\plugin_manager.py", line 474, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "D:\Minecraft\生电服\1.16.5\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins\DayCountNBT-v2.0.1.mcdr\daycount_nbt\__init__.py", line 32, in on_load
    config = server.load_config_simple('daycountNBT.json', target_class=Configure, in_data_folder=False)
  File "D:\Minecraft\生电服\1.16.5\mcdreforged\plugin\server_interface.py", line 746, in load_config_simple
    self.save_config_simple(result_config, file_name=file_name, in_data_folder=in_data_folder)
  File "D:\Minecraft\生电服\1.16.5\mcdreforged\plugin\server_interface.py", line 763, in save_config_simple
    os.makedirs(target_folder)
  File "C:\Users\Azure\AppData\Local\Programs\Python\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: ''
```

此时config文件夹内仍未创建config文件

**Comment by alex3236** [comment]
我认为这是 MCDR 问题，请到 MCDR 仓库提交 Issue.
感谢支持我的插件w
如果还有问题欢迎补充
