### ISSUE TITLE
mcdr2.0插件在cp950解码下失效

### ISSUE THREAD

**Issue by ghost** [eagle3236/daycount-NBT#3]
windows10
mcdr2.0
使用旧版无问题
新版报错
```
[MCDR] [17:11:02] [TaskExecutor/INFO] [daycount_nbt]: 读取配置文件失败，使用默认值: Expecting value: line 5 column 17 (char 114)
[MCDR] [17:11:02] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=daycount_nbt@2.0.2,priority=1000,callback=<function on_load at 0x0000024364502280>]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 474, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Python39\lib\site-packages\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins\DayCountNBT-v2.0.2.mcdr\daycount_nbt\__init__.py", line 32, in on_load
    config = server.load_config_simple(target_class=Configure)
  File "C:\Python39\lib\site-packages\mcdreforged\plugin\server_interface.py", line 746, in load_config_simple
    self.save_config_simple(result_config, file_name=file_name, in_data_folder=in_data_folder)
  File "C:\Python39\lib\site-packages\mcdreforged\plugin\server_interface.py", line 766, in save_config_simple
    json.dump(data, file, indent=4, ensure_ascii=False)
  File "C:\Python39\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
UnicodeEncodeError: 'cp950' codec can't encode character '\u8fd9' in position 1: illegal multibyte sequence
```

**Comment by alex3236** [comment]
```python
# __init__.py line 32
config = server.load_config_simple(target_class=Configure)
```
非插件问题，请向 MCDR 提交此 Issue
感谢支持w
